login: &login
  adapter: postgresql
  host: localhost
  username: alex
  password: alex
  encoding: UTF-8

development:
  database: logistic
  <<: *login

test:
  database: logistic
  <<: *login

production:
  database: logistic
  <<: *login
